server:
  port: ${SERVICE_PORT:9090}
dealFieldType: '
    XXX:Islamic Deal Product Name (Internal Identifier),
    XXX:IDFA Product Code (Internal Identifer),
    XXX:Broker A (Broker ID),
    XXX:Broker Charges/Bps,
    XXX:Commodity Code (Commodity),
    XXX:Purchase Qty of Commodity,
    XXX:Number of commodity units,
    XXX:Broker B (Broker ID),
    XXX:Profit Rate,
    XXX:Purchase Amount,
    XXX:Location of Delivery,
    XXX:Commodity Forward Price,
    XXX:Commodity Spot Price,
    XXX:Maturity Date (Commodity),
    XXX:Commodity Unit Type,
    XXX:Points,
    XXX:Related Bond Type,
    XXX:EOD Placement Currency,
    XXX:EOD Amount,
    XXX:Multiplier,
    XXX:REPO Spot Price,
    XXX:REPO Forward Price,
    500:Source of Data,
    501:Source Reference,
    501:Source Reference (Ticket No),
    502:Date of Deal,
    503:Time of Deal,
    504:Dealer ID,
    505:Date Confirmed,
    506:Time Confirmed,
    507:Confirmed-by-ID,
    508:Banking 1 Dealing Code,
    509:Bank 1 Name,
    510:Broker Dealing Code,
    511:Broker Name,
    513:Bank 2 Name,
    514:Direction,
    515:Period 1,
    516:Period 2,
    517:Currency,
    518:Currency 2,
    519:Deal Volume Currency 1,
    520:Deposit Rate,
    525:Start Date,
    527:Value Date Period 2 Currency 1,
    529:Payment Instruction Period 1 Currency 1,
    531:Payment Instruction Period 2 Currency 1,
    539:Secondary Source Reference,
    540:Method of deal,
    541:Rate Currency 1 against USD,
    543:Rate Base Currency against USD,
    544:Base Currency,
    547:Deal Volume Period 2 Currency 1,
    547:Forward Amount,
    549:Dealer Name,
    550:Confirmed-by Name,
    551:Local TCID,
    552:Review Reference Number,
    553:Comment Text,
    561:Spot Basis Rate,
    562:User-defined Title 1,
    563:User-defined Data 1,
    564:User-defined Title 2,
    565:User-defined Data 2,
    566:User-defined Title 3,
    567:ID of the original it this is a Contra,
    568:ID of previous if this is a next,
    569:Pure Deal-type,
    570:Volume of Interest,
    571:Days elapsed during Deal,
    572:Year Length,
    575:SWIFT-BIC Currency-1 Period-1,
    577:SWIFT-BIC Currency-1 Period-2,
    581:Base Currency 2,
    582:Base Currency 3,
    583:Rate Base Currency 2 versus USD,
    584:Rate Base Currency 3 versus USD,
    585:Transaction ID,
    595:Clearing House,
    596:Our Clearing Member,
    597:Their Clearing Member,
    698:On Behalf of Code,
    699:On Behalf of Name'

comodityMurabaha: '{
"Islamic Deal Product Name (Internal Identifier)":"false|true|false",
"Dealer ID":"false|true|false",
"Broker A (Broker ID)":"false|true|false",
"Broker Charges/Bps":"false|true|false",
"Commodity Code (Commodity)":"false|true|false",
"Purchase Qty of Commodity":"false|true|false",
"Number of commodity units":"false|true|false",
"Broker B (Broker ID)":"false|true|false",
"Profit Rate":"false|true|false",
"Purchase Amount":"false|true|false",
"Location of Delivery":"false|true|false",
"Commodity Forward Price":"false|true|false",
"Commodity Spot Price":"false|true|false",
"Maturity Date (Commodity)":"false|true|false",
"Commodity Unit Type":"false|true|false",
"Source of Data":"false|true|false",
"Source Reference (Ticket No)":"false|false|true",
"Date of Deal":"false|true|false",
"Time of Deal":"false|true|false",
"Date Confirmed":"false|true|false",
"Time Confirmed":"false|true|false",
"Confirmed-by-ID":"false|true|false",
"Banking 1 Dealing Code":"false|true|false",
"Bank 1 Name":"false|true|false",
"Broker Dealing Code":"false|false|true",
"Broker Name":"false|false|true",
"Bank 2 Name":"false|false|true",
"Direction":"false|true|false",
"Period 1":"false|true|false",
"Period 2":"false|false|true",
"Currency 1":"false|true|false",
"Currency 2":"false|false|true",
"Deal Volume Currency 1":"false|false|true",
"Deposit Rate":"false|false|true",
"Value Date Period 1 Currency 1":"false|true|false",
"Value Date Period 2 Currency 1":"false|true|false",
"Payment Instruction Period 1 Currency 1":"false|false|true",
"Payment Instruction Period 2 Currency 1":"false|false|true",
"Secondary Source Reference":"false|false|true",
"Method of deal":"false|false|true",
"Rate Currency 1 against USD":"false|false|true",
"Rate Base Currency against USD":"false|false|true",
"Base Currency":"false|true|false",
"Forward Amount":"false|true|false",
"Dealer Name":"false|true|false",
"Confirmed-by Name":"false|false|true",
"Local TCID":"false|true|false",
"Review Reference Number":"false|false|true",
"Comment Text":"false|false|true",
"Spot Basis Rate":"false|false|true",
"User-defined Title 1":"false|false|true",
"User-defined Data 1":"false|false|true",
"User-defined Title 2":"false|false|true",
"User-defined Data 2":"false|false|true",
"User-defined Title 3":"false|false|true",
"ID of the original it this is a Contra":"false|false|true",
"ID of previous if this is a next":"false|false|true",
"Pure Deal-type":"false|true|false",
"Volume of Interest":"false|false|true",
"Days elapsed during Deal":"false|true|false",
"Year Length":"false|true|false",
"SWIFT-BIC Currency-1 Period-1":"false|false|true",
"SWIFT-BIC Currency-1 Period-2":"false|false|true",
"Base Currency 2":"false|false|true",
"Base Currency 3":"false|false|true",
"Rate Base Currency 2 versus USD":"false|false|true",
"Rate Base Currency 3 versus USD":"false|false|true",
"Transaction ID":"false|false|true",
"Clearing House":"false|false|true",
"Our Clearing Member":"false|false|true",
"Their Clearing Member":"false|false|true",
"On Behalf of Code":"false|false|true",
"On Behalf of Name":"false|false|true"
}'

Wakala: '{
"IDFA Product Code (Internal Identifer)":"false|true|false",
"Dealer ID":"false|true|false",
"Profit Rate":"true|true|false",
"Source of Data":"false|true|false",
"Source Reference":"false|false|true",
"Date of Deal":"true|true|false",
"Time of Deal":"true|true|false",
"Date Confirmed":"true|true|false",
"Time Confirmed":"true|true|false",
"Confirmed-by-ID":"false|true|false",
"Banking 1 Dealing Code":"false|true|false",
"Bank 1 Name":"false|true|false",
"Broker Dealing Code":"false|false|true",
"Broker Name":"false|false|true",
"Bank 2 Name":"false|false|true",
"Direction":"false|true|false",
"Period 1":"true|false|false",
"Period 2":"false|true|true",
"Currency 1":"true|false|false",
"Currency 2":"false|true|true",
"Deal Volume Currency 1":"false|true|true",
"Deposit Rate":"false|true|true",
"Value Date Period 1 Currency 1":"true|false|false",
"Value Date Period 2 Currency 1":"true|false|false",
"Payment Instruction Period 1 Currency 1":"false|true|true",
"Payment Instruction Period 2 Currency 1":"false|true|true",
"Secondary Source Reference":"false|true|true",
"Method of deal":"false|true|true",
"Rate Currency 1 against USD":"false|true|true",
"Rate Base Currency against USD":"false|true|true",
"Base Currency":"true|false|false",
"Deal Volume Period 2 Currency 1":"false|true|false",
"Dealer Name":"true|false|false",
"Confirmed-by Name":"false|true|true",
"Local TCID":"true|false|false",
"Review Reference Number":"false|true|true",
"Comment Text":"false|true|true",
"Spot Basis Rate":"false|true|true",
"User-defined Title 1":"false|true|true",
"User-defined Data 1":"false|true|true",
"User-defined Title 2":"false|true|true",
"User-defined Data 2":"false|true|true",
"User-defined Title 3":"false|true|true",
"ID of the original it this is a Contra":"false|true|true",
"ID of previous if this is a next":"false|true|true",
"Pure Deal-type":"true|false|false",
"Volume of Interest":"false|true|true",
"Days elapsed during Deal":"true|false|false",
"Year Length":"true|false|false",
"SWIFT-BIC Currency-1 Period-1":"false|true|true",
"SWIFT-BIC Currency-1 Period-2":"false|true|true",
"Base Currency 2":"false|true|true",
"Base Currency 3":"false|true|true",
"Rate Base Currency 2 versus USD":"false|true|true",
"Rate Base Currency 3 versus USD":"false|true|true",
"Transaction ID":"false|true|true",
"Clearing House":"false|true|true",
"Our Clearing Member":"false|true|true",
"Their Clearing Member":"false|true|true",
"On Behalf of Code":"false|true|true",
"On Behalf of Name":"false|true|true"
}'

Mudaraba: '{
"IDFA Product Code (Internal Identifer)":"false|true|false",
"Dealer ID":"false|true|false",
"Profit Rate":"true|true|false",
"Source of Data":"false|true|false",
"Source Reference":"false|false|true",
"Date of Deal":"true|true|false",
"Time of Deal":"true|true|false",
"Date Confirmed":"true|true|false",
"Time Confirmed":"true|true|false",
"Confirmed-by-ID":"false|true|false",
"Banking 1 Dealing Code":"false|true|false",
"Bank 1 Name":"false|true|false",
"Broker Dealing Code":"false|false|true",
"Broker Name":"false|false|true",
"Bank 2 Name":"false|false|true",
"Direction":"false|true|false",
"Period 1":"true|false|false",
"Period 2":"false|true|true",
"Currency 1":"true|false|false",
"Currency 2":"false|true|true",
"Deal Volume Currency 1":"false|true|true",
"Deposit Rate":"false|true|true",
"Value Date Period 1 Currency 1":"true|false|false",
"Value Date Period 2 Currency 1":"true|false|false",
"Payment Instruction Period 1 Currency 1":"false|true|true",
"Payment Instruction Period 2 Currency 1":"false|true|true",
"Secondary Source Reference":"false|true|true",
"Method of deal":"false|true|true",
"Rate Currency 1 against USD":"false|true|true",
"Rate Base Currency against USD":"false|true|true",
"Base Currency":"true|false|false",
"Deal Volume Period 2 Currency 1":"false|true|false",
"Dealer Name":"true|false|false",
"Confirmed-by Name":"false|true|true",
"Local TCID":"true|false|false",
"Review Reference Number":"false|true|true",
"Comment Text":"false|true|true",
"Spot Basis Rate":"false|true|true",
"User-defined Title 1":"false|true|true",
"User-defined Data 1":"false|true|true",
"User-defined Title 2":"false|true|true",
"User-defined Data 2":"false|true|true",
"User-defined Title 3":"false|true|true",
"ID of the original it this is a Contra":"false|true|true",
"ID of previous if this is a next":"false|true|true",
"Pure Deal-type":"true|false|false",
"Volume of Interest":"false|true|true",
"Days elapsed during Deal":"true|false|false",
"Year Length":"true|false|false",
"SWIFT-BIC Currency-1 Period-1":"false|true|true",
"SWIFT-BIC Currency-1 Period-2":"false|true|true",
"Base Currency 2":"false|true|true",
"Base Currency 3":"false|true|true",
"Rate Base Currency 2 versus USD":"false|true|true",
"Rate Base Currency 3 versus USD":"false|true|true",
"Transaction ID":"false|true|true",
"Clearing House":"false|true|true",
"Our Clearing Member":"false|true|true",
"Their Clearing Member":"false|true|true",
"On Behalf of Code":"false|true|true",
"On Behalf of Name":"false|true|true"
}'

pbd: '{
  "IDFA Product Code (Internal Identifer)":"false|true|false",
  "Dealer ID":"false|true|false",
  "Points":"true|true|false",
  "Source of Data":"false|true|false",
  "Source Reference":"false|false|true",
  "Date of Deal":"true|true|false",
  "Time of Deal":"true|true|false",
  "Date Confirmed":"true|true|false",
  "Time Confirmed":"true|true|false",
  "Confirmed-by-ID":"false|true|false",
  "Banking 1 Dealing Code":"false|true|false",
  "Bank 1 Name":"false|true|false",
  "Broker Dealing Code":"false|false|true",
  "Broker Name":"false|false|true",
  "Bank 2 Name":"false|false|true",
  "Direction":"false|true|false",
  "Period 1":"true|false|false",
  "Period 2":"false|true|true",
  "Currency 1":"true|false|false",
  "Currency 2":"false|true|true",
  "Deal Volume Currency 1":"false|true|true",
  "Deposit Rate":"false|true|true",
  "Value Date Period 1 Currency 1":"true|false|false",
  "Value Date Period 2 Currency 1":"true|false|false",
  "Payment Instruction Period 1 Currency 1":"false|true|true",
  "Payment Instruction Period 2 Currency 1":"false|true|true",
  "Secondary Source Reference":"false|true|true",
  "Method of deal":"false|true|true",
  "Rate Currency 1 against USD":"false|true|true",
  "Rate Base Currency against USD":"false|true|true",
  "Base Currency":"true|false|false",
  "Deal Volume Period 2 Currency 1":"false|true|false",
  "Dealer Name":"true|false|false",
  "Confirmed-by Name":"false|true|true",
  "Local TCID":"true|false|false",
  "Review Reference Number":"false|true|true",
  "Comment Text":"false|true|true",
  "Spot Basis Rate":"false|true|true",
  "User-defined Title 1":"false|true|true",
  "User-defined Data 1":"false|true|true",
  "User-defined Title 2":"false|true|true",
  "User-defined Data 2":"false|true|true",
  "User-defined Title 3":"false|true|true",
  "ID of the original it this is a Contra":"false|true|true",
  "ID of previous if this is a next":"false|true|true",
  "Pure Deal-type":"true|false|false",
  "Volume of Interest":"false|true|true",
  "Days elapsed during Deal":"true|false|false",
  "Year Length":"true|false|false",
  "SWIFT-BIC Currency-1 Period-1":"false|true|true"
}'

repo: '{
  "IDFA Product Code (Internal Identifer)":"false|true|false",
  "Dealer ID":"false|true|false",
  "REPO Spot Price":"true|true|false",
  "REPO Forward Price":"true|true|false",
  "Related Bond Type":"true|true|false",
  "Source of Data":"false|true|false",
  "Source Reference":"false|false|true",
  "Date of Deal":"true|true|false",
  "Time of Deal":"true|true|false",
  "Date Confirmed":"true|true|false",
  "Time Confirmed":"true|true|false",
  "Confirmed-by-ID":"false|true|false",
  "Banking 1 Dealing Code":"false|true|false",
  "Bank 1 Name":"false|true|false",
  "Broker Dealing Code":"false|false|true",
  "Broker Name":"false|false|true",
  "Bank 2 Name":"false|false|true",
  "Direction":"false|true|false",
  "Period 1":"true|false|false",
  "Period 2":"false|true|true",
  "Currency 1":"true|false|false",
  "Currency 2":"false|true|true",
  "Deal Volume Currency 1":"false|true|true",
  "Deposit Rate":"false|true|true",
  "Value Date Period 1 Currency 1":"true|false|false",
  "Value Date Period 2 Currency 1":"true|false|false",
  "Payment Instruction Period 1 Currency 1":"false|true|true",
  "Payment Instruction Period 2 Currency 1":"false|true|true",
  "Secondary Source Reference":"false|true|true",
  "Method of deal":"false|true|true",
  "Rate Currency 1 against USD":"false|true|true",
  "Rate Base Currency against USD":"false|true|true",
  "Base Currency":"true|false|false",
  "Deal Volume Period 2 Currency 1":"false|true|false",
  "Dealer Name":"true|false|false",
  "Confirmed-by Name":"false|true|true",
  "Local TCID":"true|false|false",
  "Review Reference Number":"false|true|true",
  "Comment Text":"false|true|true",
  "Spot Basis Rate":"false|true|true",
  "User-defined Title 1":"false|true|true",
  "User-defined Data 1":"false|true|true",
  "User-defined Title 2":"false|true|true",
  "User-defined Data 2":"false|true|true",
  "User-defined Title 3":"false|true|true"
}'

eod: '{
  "Islamic Deal Product Name (Internal Identifier)":"false|true|false",
  "Dealer ID":"false|true|false",
  "Ticket No":"false|true|false",
  "Client / Deal Type":"true|false|false",
  "Quantity":"true|false|false",
  "Broker A (Broker ID)":"true|false|false",
  "Broker Charges/Bps":"true|false|false",
  "Commodity Code (Commodity)":"true|false|false",
  "Broker B (Broker ID)":"true|false|false",
  "Purchase Amount":"true|false|false",
  "Location of Delivery":"true|false|false",
  "Commodity Spot Price":"true|false|false",
  "Maturity Date (Commodity)":"true|false|false",
  "Commodity Unit Type":"true|false|false",
  "Points":"true|false|false",
  "Related Bond Type":"true|false|false",
  "Multiplier":"true|false|false",
  "EOD Amount":"true|false|false",
  "EOD Placement Currency":"true|false|false",
  "Source of Data":"false|true|false",
  "Source Reference":"false|true|false",
  "Deal Time":"false|true|false",
  "Time Confirmed":"false|true|false",
  "Confirmed-by-ID":"false|true|false",
  "Broker Dealing Code":"false|true|false",
  "Broker Name":"false|true|false",
  "Bank 2 Name":"false|true|false",
  "Direction":"false|true|false",
  "Period 1":"false|true|false",
  "Period 2":"false|true|false",
  "Currency":"false|true|false",
  "Currency 2":"false|true|false",
  "Amount":"false|true|false",
  "Profit Rate":"false|true|false",
  "Start Date":"false|true|false",
  "Maturity":"false|true|false",
  "Payment Instruction Period 1 Currency 1":"false|true|false",
  "Payment Instruction Period 2 Currency 1":"false|true|false",
  "Secondary Source Reference":"false|true|false",
  "Method of deal":"false|true|false",
  "Rate Currency 1 against USD":"false|true|false",
  "Rate Base Currency against USD":"false|true|false",
  "Base Currency":"false|true|false",
  "Forward Amount":"false|true|false",
  "Dealer Name":"false|true|false",
  "Confirmed-by Name":"false|true|false",
  "Local Desk":"false|true|false",
  "Review Reference Number":"false|true|false",
  "Comment Text":"false|true|false",
  "Spot Basis Rate":"false|true|false",
  "User-defined Title 1":"false|true|false",
  "User-defined Data 1":"false|true|false",
  "User-defined Title 2":"false|true|false",
  "User-defined Data 2":"false|true|false",
  "User-defined Title 3":"false|true|false",
  "User-defined Data 3":"false|true|false",
  "ID of the original if this is a Contra":"false|true|false",
  "ID of previous if this is a next":"false|true|false",
  "Deal Type":"false|true|false",
  "Volume of Interest":"false|true|false",
  "Days Elapsed":"false|true|false",
  "Year Length":"false|true|false",
  "SWIFT-BIC Currency-1 Period-1":"false|true|false",
  "SWIFT-BIC Currency-1 Period-2":"false|true|false",
  "Base Currency 2":"false|true|false",
  "Base Currency 3":"false|true|false",
  "Rate Base Currency 2 versus USD":"false|true|false",
  "Rate Base Currency 3 versus USD":"false|true|false",
  "Transaction ID":"false|true|false",
  "Clearing House":"false|true|false",
  "Our Clearing Member":"false|true|false",
  "Their Clearing Member":"false|true|false",
  "On Behalf of Code":"false|true|false",
  "On Behalf of Name":"false|true|false",
  "Link ID":"false|true|false"
}'
