runtime: java
env: flex
runtime_config:
  jdk: openjdk8
handlers:
  - url: /.*
    script: this field is required, but ignored

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 3.75
  disk_size_gb: 10

#liveness_check:
#  check_interval_sec: 120
#  timeout_sec: 40
#  failure_threshold: 5
#  success_threshold: 5
#  initial_delay_sec: 3500
#
#readiness_check:
#  check_interval_sec: 120
#  timeout_sec: 40
#  failure_threshold: 5
#  success_threshold: 5
#  app_start_timeout_sec: 3500

## Application Resources
#resources:
#  cpu: 2
#  memory_gb: 2
#  disk_size_gb: 10
#  volumes:
#    - name: ramdisk1
#      volume_type: tmpfs
#      size_gb: 0.5
## Automatic Scaling
#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 4
#  cool_down_period_sec: 180
#  cpu_utilization:
#    target_utilization: 0.6